<p class="clear">

<br />

<h1><strong>CM Answers Pro </strong></h1>

 <p><strong>A Pro version of CM Answers is <a href="https://www.cminds.com/cm-answer-store-page-content/"  target="_blank">available here</a></strong></p>



 <br><br>

<h1><strong>Video Demo </strong></h1>

<iframe width="427" height="240" src="http://www.youtube.com/embed/w6w3zyfi7-c?rel=0" frameborder="0" allowfullscreen></iframe>

<iframe width="427" height="240" src="http://www.youtube.com/embed/d2mar0NrPb8?rel=0" frameborder="0" allowfullscreen></iframe>



 <h2>Features (Pro Version Only)</h2>

<div style="height:10px;"></div>

<h4>General Settings</h4>

<ul>

	<li>[New] <strong>Categories Support</strong> - Support two level categories navigation</strong>. </li>

	<li><strong>Categories</strong>- Ability to add categories and display them using a Shortcode. cat=catname</li>

	<li><strong>Multisite</strong>- Supports multisites.</li>

	<li><strong>Localization Support</strong> - Frontend (user side) is localized.</li>

	<li><strong>Homepage</strong> - Supports options to define CM Answers as the Site or Blog homepage</li>

	<li><strong>Permalink</strong> - Customizable CM Answers permalink.</li>

	<li><strong>Disclaimer</strong> -Added Disclaimer support for first time users.</li>

	<li><strong>Gratitude Message</strong> - Does not include our Gratitude Message in the footer.</li>

</ul>



<div style="height:10px;"></div>

<h4>Access Restriction & Moderation</h4>

<ul>

<li>[New]<strong>Access Control</strong>- Admin can define who can ask questions and who can answer based on user role. </li>

	<li><strong>Moderation</strong>- Administrators can define a list of users who are exempt and can post without any need of moderation. (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image7.png" target="new">image</a>)</li>

</ul>



<div style="height:10px;"></div>

<h4>Shortocdes & Widgets</h4>

<ul>

	<li><strong>Shortcodes</strong>- Generates a Questions List by using a Shortcode: cma-questions with additional parameters. For example, limit=10 author=123 sort=hottest </li>

	<li><strong>Widgets</strong>- Widget integration that can sort and display hottest questions, most viewed, most recent answers and more.</li>

</ul>



<div style="height:10px;"></div>

<h4>User Management</h4>

<ul>

	<li>[New] <strong>BuddyPress</strong> - Integration with <strong>BoddyPress</strong>. </li>

	<li><strong>Social Media Registration Integration</strong>- Integrates with Facebook, Google+, Twitter, Microsoft Live and LinkedIn profiles. (<a href="http://www.cminds.com/wp-content/uploads/edd/image1.png" target="new">image-1</a>) (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image2.png" target="new">image-2</a>)</li>

	<li><strong>User Dashboard</strong>- Adds "My Questions" and "My Answers" dashboards to the user profile page by using Shortcodes: cma-my-questions and cma-my-answers. (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image3.png" target="new">image</a>)</li>

	<li><strong>Public User Profile</strong>- Automatically generates a public profile page containing all the questions and answers a user has posted, with a link to his or her social media profile.</li>

	<li><strong>Gravatar</strong> - Ability to display a Gravatar near the user's name and in the user's profile. </li>

	<li><strong>User Posting Meter</strong> -Ability to add the user's profile of the number of posted questions and answers that the user has contributed displayed beside their user name. (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image5.png" target="new">image</a>)</li>

</ul>



<div style="height:10px;"></div>

<h4>Questions Management</h4>

<ul>

	<li>[New] <strong>Mark Question as Resolved</strong> - Question author can mark question as resolved. </li>

	<li><strong>Order Answers</strong> - Shows and sorts all answers in ascending or descending order.</li>

	<li><strong>Attachments</strong> - Accepts file attachments when posting a question. Limits for file types and sizes.</li>

	<li><strong>Text Editor</strong> - Includes a full text editor for questions and answers</li>

	<li><strong>Edit Questions or Answer</strong> - Question or Answers can be edited after posting</li>

	<li><strong>Tags</strong> - Tags are fully supported. Administrators can control the appearance of tags with an available Tags widget.</li>

	<li><strong>Sticky Questions</strong> - Supports sticky questions with an administrator defined background color. </li>

	<li><strong>Show/Hide Views</strong>- Administrator can choose to hide or show the number of views that a topic has. (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image6.png" target="new">image</a>)</li>

	<li><strong>View Count Control</strong> - Controls how a view count is tabulated (by view or by session). </li>

	<li><strong>Ajax Support</strong> - Uses a Shortcode that displays the Category, supported by Ajax. Views of categories fit within the current site template.</li>

	<li><strong>Code Snippets in Posts</strong> -  Support for code snippets and custom background color. </li>

	<li><strong>Social Share</strong> - Includes a social share widget in the question page.</li>

</ul>





<h1><strong>Purchase </strong></h1>

<p>You can purchase the pro version from <a href="https://www.cminds.com/cm-answer-store-page-content/">Here</a></p>





</p>